<script setup lang="ts">
import { ref } from 'vue';

useHead({
  title: 'Never Have I Ever',
  meta: [
    {
      name: 'description',
      content: 'A fun drinking game where players reveal things they have never done.'
    }
  ]
});

// Predefined Never Have I Ever prompts
const prompts = ref([
  'Never have I ever gone skydiving.',
  'Never have I ever broken a bone.',
  'Never have I ever been on a boat.',
  'Never have I ever eaten sushi.',
  'Never have I ever gone camping.',
  'Never have I ever skipped school.',
  'Never have I ever failed a test.',
  'Never have I ever gotten a speeding ticket.',
  'Never have I ever traveled abroad.',
  'Never have I ever dyed my hair.',
  'Never have I ever stayed up all night.',
  'Never have I ever been on a roller coaster.',
  'Never have I ever gone scuba diving.',
  'Never have I ever ridden a horse.',
  'Never have I ever sung karaoke.',
  'Never have I ever been to a concert.',
  'Never have I ever been in a relationship.',
  'Never have I ever told a lie.',
  'Never have I ever run a marathon.',
  'Never have I ever been on a blind date.',
  'Never have I ever eaten a bug.',
  'Never have I ever been in a fight.',
  'Never have I ever been to Disneyland.',
  'Never have I ever watched a horror movie alone.',
  'Never have I ever gone skinny dipping.',
  'Never have I ever stayed in a 5-star hotel.',
  'Never have I ever met a celebrity.',
  'Never have I ever been on a road trip.',
  'Never have I ever used a fake ID.',
  'Never have I ever fallen asleep in public.',
  'Never have I ever cried during a movie.',
  'Never have I ever laughed so hard I cried.',
  'Never have I ever been scuba diving.',
  'Never have I ever bungee jumped.',
  'Never have I ever been to a music festival.',
  'Never have I ever stayed awake for more than 24 hours.',
  'Never have I ever danced in the rain.',
  'Never have I ever eaten a whole pizza by myself.',
  'Never have I ever been ice skating.',
  'Never have I ever gotten a tattoo.',
  'Never have I ever lied to a boss.',
  'Never have I ever been fired from a job.',
  'Never have I ever been seasick.',
  'Never have I ever made a YouTube video.',
  'Never have I ever seen snow.',
  'Never have I ever been skiing.',
  'Never have I ever played poker.',
  'Never have I ever pulled an all-nighter studying.',
  'Never have I ever driven a motorcycle.',
  'Never have I ever been on TV.',
  'Never have I ever been on a cruise ship.',
  'Never have I ever fainted.',
  'Never have I ever hitchhiked.',
  'Never have I ever lied about my age.',
  'Never have I ever been to a tropical island.',
  'Never have I ever climbed a mountain.',
  'Never have I ever gone zip-lining.',
  'Never have I ever sent a text to the wrong person.',
  'Never have I ever used a dating app.',
  'Never have I ever been to a spa.',
  'Never have I ever had food poisoning.',
  'Never have I ever been in a helicopter.',
  'Never have I ever sung in front of an audience.',
  'Never have I ever traveled first class.',
  'Never have I ever had a near-death experience.',
  'Never have I ever won a contest.',
  'Never have I ever eaten escargot.',
  'Never have I ever taken a selfie with an animal.',
  'Never have I ever lost my phone.',
  'Never have I ever owned a pet.',
  'Never have I ever ridden a mechanical bull.',
  'Never have I ever seen a shooting star.',
  'Never have I ever been skydiving.',
  'Never have I ever been to a drive-in movie.',
  'Never have I ever ridden a camel.',
  'Never have I ever had surgery.',
  'Never have I ever been to a foreign country.',
  'Never have I ever missed a flight.',
  'Never have I ever fainted at the sight of blood.',
  'Never have I ever had a surprise party thrown for me.',
  'Never have I ever broken up with someone.',
  'Never have I ever been in love.',
  'Never have I ever lied to a friend.',
  'Never have I ever been ghosted by someone.',
  'Never have I ever lost a bet.',
  'Never have I ever built a snowman.',
  'Never have I ever been snorkeling.',
  'Never have I ever seen a wild animal up close.',
  'Never have I ever gone on a road trip with friends.',
  'Never have I ever dyed my hair a crazy color.',
  'Never have I ever played a prank on someone.',
  'Never have I ever been to a casino.',
  'Never have I ever stayed in a hostel.',
  'Never have I ever been to a Broadway show.',
  'Never have I ever run a 5K.',
  'Never have I ever participated in a talent show.',
  'Never have I ever taken a cooking class.',
  'Never have I ever learned to play a musical instrument.',
  'Never have I ever won a game of Monopoly.',
  'Never have I ever been to a sporting event.',
  'Never have I ever gone paddleboarding.',
  'Never have I ever slept on the beach.',
  'Never have I ever seen a live concert.',
  'Never have I ever gone vegan.',
  'Never have I ever done a photoshoot.',
  'Never have I ever stayed up past 3 a.m.',
  'Never have I ever eaten breakfast for dinner.',
  'Never have I ever been scuba diving.',
  'Never have I ever watched an entire TV series in one day.',
  'Never have I ever gone to a midnight movie premiere.',
  'Never have I ever had a paranormal experience.',
  'Never have I ever been pulled over by the police.',
  'Never have I ever been in a car accident.',
  'Never have I ever played a team sport.',
  'Never have I ever eaten something I regretted later.',
  'Never have I ever won a trivia game.',
  'Never have I ever ridden in a limousine.',
  'Never have I ever been stuck in an elevator.',
  'Never have I ever watched a movie more than 10 times.',
  'Never have I ever been on a hot air balloon ride.',
  'Never have I ever seen a double rainbow.',
  'Never have I ever fallen asleep during a meeting.',
  'Never have I ever tried to start a business.',
  'Never have I ever sent a postcard.',
  'Never have I ever eaten a whole cake by myself.',
  'Never have I ever been to a water park.',
  'Never have I ever won a raffle.',
  'Never have I ever had a pen pal.',
  'Never have I ever stayed at a bed and breakfast.',
  'Never have I ever gone on a safari.',
  'Never have I ever performed in a play.',
  'Never have I ever solved a Rubik’s cube.',
  'Never have I ever made a snow angel.',
  'Never have I ever had a hangover.',
  'Never have I ever been on a sailboat.',
  'Never have I ever eaten a ghost pepper.',
  'Never have I ever stayed in an Airbnb.',
  'Never have I ever been a maid of honor or best man.',
  'Never have I ever cooked a holiday meal.',
  'Never have I ever played video games all day.',
  'Never have I ever been a bridesmaid or groomsman.',
  'Never have I ever tried sushi.',
  'Never have I ever binge-watched a series in one sitting.',
  'Never have I ever missed a wedding.',
  'Never have I ever eaten an entire pizza in one sitting.',
  'Never have I ever climbed a tree.',
  'Never have I ever made a viral video.',
  'Never have I ever been bungee jumping.',
  'Never have I ever walked out of a movie theater.',
  'Never have I ever lost my wallet.',
  'Never have I ever gone vegan or vegetarian for a week.',
  'Never have I ever been to a Renaissance Fair.',
  'Never have I ever gone jet skiing.',
  'Never have I ever been to the Grand Canyon.',
  'Never have I ever seen a volcano in person.',
  'Never have I ever been to a different continent.',
  'Never have I ever been to a theme park.',
  'Never have I ever been in a musical.',
  'Never have I ever gone surfing.',
  'Never have I ever done yoga.',
  'Never have I ever stayed at a haunted hotel.',
  'Never have I ever taken a road trip by myself.',
  'Never have I ever taken a helicopter tour.',
  'Never have I ever been whale watching.',
  'Never have I ever watched the sunrise.',
  'Never have I ever hosted a dinner party.',
  'Never have I ever been late to a wedding.',
  'Never have I ever had a surprise birthday party.',
  'Never have I ever met a famous musician.',
  'Never have I ever had a picnic in the park.',
  'Never have I ever performed karaoke in a bar.',
  'Never have I ever been to a haunted house.',
  'Never have I ever seen a whale in the wild.',
  'Never have I ever gotten lost in a foreign country.',
  'Never have I ever been to a fashion show.',
  'Never have I ever taken a pottery class.',
  'Never have I ever done archery.',
  'Never have I ever made a scrapbook.',
  'Never have I ever written a poem.',
  'Never have I ever been ziplining.',
  'Never have I ever baked bread from scratch.',
  'Never have I ever run a 10K.',
  'Never have I ever gone horseback riding on the beach.',
  'Never have I ever made a wish at a fountain.',
  'Never have I ever been to a bar alone.',
  'Never have I ever been scuba diving or snorkeling.',
  'Never have I ever gone to a music festival.',
  'Never have I ever learned a new language.',
  'Never have I ever played in a band.',
  'Never have I ever been to a historical monument.',
  'Never have I ever donated blood.',
  'Never have I ever given a speech at a wedding.',
  'Never have I ever gone ice fishing.',
  'Never have I ever been on a horse.',
  'Never have I ever ridden a motorcycle.',
  'Never have I ever made a bucket list.',
  'Never have I ever swum with dolphins.',
  'Never have I ever hitchhiked.',
  'Never have I ever been to a national park.',
  'Never have I ever slept outside under the stars.',
  'Never have I ever driven a stick shift.',
  'Never have I ever stayed awake for more than 48 hours.',
  'Never have I ever dyed my hair a bright color.',
  'Never have I ever been to a famous landmark.',
  'Never have I ever won a game show.',
  'Never have I ever been in a car accident.',
  'Never have I ever eaten food from a food truck.',
  'Never have I ever been to a vineyard.',
  'Never have I ever attended a surprise party.',
  'Never have I ever painted a picture.',
  'Never have I ever been to a foreign country.',
  'Never have I ever been on a road trip.',
  'Never have I ever seen a polar bear.',
  'Never have I ever been to a circus.',
  'Never have I ever built a treehouse.',
  'Never have I ever been to a masquerade ball.',
  'Never have I ever flown in a private jet.',
  'Never have I ever been on a ghost tour.',
  'Never have I ever stayed in a cabin in the woods.',
  'Never have I ever gone white-water rafting.',
  'Never have I ever been in a flash mob.',
  'Never have I ever taken a photo with a celebrity.',
  'Never have I ever been to a planetarium.',
  'Never have I ever taken a selfie with a stranger.',
  'Never have I ever been to a costume party.',
  'Never have I ever stayed at a luxury hotel.',
  'Never have I ever traveled solo.',
  'Never have I ever been in a hot tub in winter.',
  'Never have I ever visited all seven continents.',
  'Never have I ever gone rock climbing.',
  'Never have I ever visited a famous movie set.',
  'Never have I ever gotten a henna tattoo.',
  'Never have I ever been on a road trip with family.',
  'Never have I ever danced in a conga line.',
  'Never have I ever taken a group photo with strangers.',
  'Never have I ever visited an art museum.',
  'Never have I ever taken a selfie in front of a famous monument.',
  'Never have I ever made homemade ice cream.',
  'Never have I ever attended a comedy show.',
  'Never have I ever been to a food festival.',
  'Never have I ever been on a private boat.',
  'Never have I ever danced with a stranger.',
  'Never have I ever gone to a karaoke bar alone.',
  'Never have I ever watched a live sporting event.',
  'Never have I ever visited a castle.',
  'Never have I ever swam in an infinity pool.',
  'Never have I ever won a costume contest.',
  'Never have I ever made my own pizza from scratch.',
  'Never have I ever taken a cooking class abroad.',
  'Never have I ever been to a rooftop bar.',
  'Never have I ever walked on a frozen lake.',
  'Never have I ever seen a shooting star.',
  'Never have I ever seen the Northern Lights.',
  'Never have I ever climbed a volcano.',
  'Never have I ever been to an aquarium.',
  'Never have I ever spent a night in the desert.',
  'Never have I ever learned to dance salsa.',
  'Never have I ever visited a famous lighthouse.',
  'Never have I ever been in a reality TV show audience.',
  'Never have I ever eaten a deep-fried Twinkie.',
  'Never have I ever visited the Great Wall of China.',
  'Never have I ever taken a solo hiking trip.',
  'Never have I ever been to an outdoor concert.',
  'Never have I ever done stand-up comedy.',
  'Never have I ever visited a famous prison.',
  'Never have I ever walked across a famous bridge.',
  'Never have I ever played in a trivia competition.',
  'Never have I ever taken a cooking class for fun.',
  'Never have I ever visited a world heritage site.',
  'Never have I ever eaten street food abroad.',
  'Never have I ever gone on a scavenger hunt.',
  'Never have I ever danced with a stranger at a wedding.',
  'Never have I ever visited a vineyard abroad.',
  'Never have I ever participated in a charity run.',
  'Never have I ever swum with sea turtles.',
  'Never have I ever been in a yacht.',
  'Never have I ever baked a pie from scratch.',
  'Never have I ever gone snowshoeing.',
  'Never have I ever gone to a masquerade party.',
  'Never have I ever gone to a farmer’s market.',
  'Never have I ever participated in a beach cleanup.',
  'Never have I ever been on a fishing trip.',
  'Never have I ever taken part in a flash mob.',
  'Never have I ever gone to a professional baseball game.',
  'Never have I ever attended a virtual concert.',
  'Never have I ever gone on a city tour.',
  'Never have I ever had a spa day with friends.',
  'Never have I ever gone tubing in a river.',
  'Never have I ever climbed a waterfall.',
  'Never have I ever had a virtual happy hour.',
  'Never have I ever been to a themed restaurant.',
  'Never have I ever seen a Broadway show in person.',
  'Never have I ever traveled to a tropical island.',
  'Never have I ever had a movie marathon with friends.',
  'Never have I ever attended a drive-in concert.',
  'Never have I ever played virtual reality games.',
  'Never have I ever had a virtual wine tasting.',
  'Never have I ever watched a sunrise on the beach.',
  'Never have I ever swam in a waterfall.',
  'Never have I ever taken a gondola ride in Venice.',
  'Never have I ever attended a virtual wedding.',
  'Never have I ever gone skiing in the Alps.',
  'Never have I ever traveled by train.',
  'Never have I ever had a virtual cooking class.',
  'Never have I ever been to a street art festival.',
  'Never have I ever had an at-home spa day.',
  'Never have I ever attended a virtual baby shower.',
  'Never have I ever been to an open-air market.',
  'Never have I ever taken a long walk on the beach at sunset.',
  'Never have I ever had a breakfast picnic.',
  'Never have I ever gone swimming at night.',
  'Never have I ever had a campfire on the beach.',
  'Never have I ever gone stargazing in the desert.',
  'Never have I ever taken a romantic getaway.',
  'Never have I ever eaten pizza in Italy.',
  'Never have I ever attended a wine festival.',
  'Never have I ever been to a rooftop restaurant.',
  'Never have I ever had a surprise dinner party.',
  'Never have I ever danced barefoot in the grass.',
  'Never have I ever had a picnic in a vineyard.',
  'Never have I ever had a candlelight dinner outdoors.',
  'Never have I ever had breakfast in bed in a hotel.',
  'Never have I ever stayed in a treehouse hotel.',
  'Never have I ever attended a music festival in another country.',
  'Never have I ever stayed in a castle hotel.',
  'Never have I ever had a sunset cocktail on the beach.',
  'Never have I ever taken a yoga class on the beach.',
  'Never have I ever done a wine tasting tour.',
  'Never have I ever attended a pop-up restaurant.',
  'Never have I ever stayed at a luxury resort.',
  'Never have I ever visited a national park in another country.',
  'Never have I ever attended a live cooking show.',
  'Never have I ever taken a culinary tour in another country.',
  'Never have I ever watched a fireworks show on the beach.',
  'Never have I ever taken a sunrise hot air balloon ride.',
  'Never have I ever had a moonlit picnic.',
  'Never have I ever gone hiking in a national forest.',
  'Never have I ever had a private chef cook dinner at home.',
  'Never have I ever gone on a spontaneous weekend getaway.',
  'Never have I ever eaten dinner in a cave restaurant.',
  'Never have I ever visited a world-famous aquarium.',
  'Never have I ever stayed at an eco-lodge.',
  'Never have I ever attended a sunrise yoga class.',
  'Never have I ever gone to a themed dinner party.',
  'Never have I ever taken a scenic train ride.',
  'Never have I ever visited a food hall.',
  'Never have I ever had an impromptu dance party at home.',
  'Never have I ever attended a silent disco.',
  'Never have I ever gone on a spontaneous road trip.',
  'Never have I ever attended a rooftop movie screening.',
  'Never have I ever taken a virtual art class.',
  'Never have I ever stayed at a desert resort.',
  'Never have I ever visited a rooftop pool.',
  'Never have I ever attended a live virtual concert.',
  'Never have I ever gone on a scenic drive through the mountains.',
  'Never have I ever had a beach bonfire.',
  'Never have I ever attended a secret pop-up event.',
  'Never have I ever eaten at a Michelin-starred restaurant.',
  'Never have I ever had breakfast on a rooftop.',
  'Never have I ever gone to a vineyard for wine tasting.',
  'Never have I ever danced at a silent disco.',
  'Never have I ever been to a food truck festival.',
  'Never have I ever taken a tour of a historical mansion.',
  'Never have I ever been on a cross-country road trip.',
  'Never have I ever visited a lighthouse.',
  'Never have I ever attended a rooftop bar party.',
  'Never have I ever stayed at a farm-to-table resort.',
  'Never have I ever attended a vineyard wedding.',
  'Never have I ever visited a historical castle.',
  'Never have I ever taken a hot air balloon ride at sunrise.',
  'Never have I ever had a private beach picnic.',
  'Never have I ever attended a concert in another country.',
  'Never have I ever gone on a scenic bike ride.',
  'Never have I ever had a private wine tasting at a vineyard.',
  'Never have I ever been to a rooftop pool party.',
  'Never have I ever had a sunset beach picnic.',
  'Never have I ever stayed at a beachfront villa.',
  'Never have I ever attended a themed dinner event.',
  'Never have I ever gone on a nature walk.',
  'Never have I ever gone on a boat tour at sunset.',
  'Never have I ever attended a pop-up dinner in a secret location.',
  'Never have I ever had a private yoga session on the beach.',
  'Never have I ever attended a silent auction.',
  'Never have I ever been to a vineyard tour and tasting.',
  'Never have I ever attended a rooftop brunch.',
  'Never have I ever been on a private yacht.',
  'Never have I ever attended a rooftop dinner party.',
  'Never have I ever danced under the stars.',
  'Never have I ever taken a scenic helicopter ride.',
  'Never have I ever attended a food and wine festival.',
  'Never have I ever had a beach bonfire with friends.',
  'Never have I ever taken a private hot air balloon ride.',
  'Never have I ever visited a rooftop vineyard.',
  'Never have I ever attended a pop-up art gallery.',
  'Never have I ever attended a rooftop concert.',
  'Never have I ever stayed at a beach house.',
  'Never have I ever taken a private boat tour at sunset.',
  'Never have I ever had a moonlit dinner on the beach.',
  'Never have I ever gone hiking at sunrise.',
  'Never have I ever attended a themed brunch party.',
  'Never have I ever taken a private cooking class on vacation.',
  'Never have I ever had a sunset dinner on the beach.',
  'Never have I ever taken a beach yoga class.',
  'Never have I ever visited a private vineyard.',
  'Never have I ever attended a secret rooftop party.',
  'Never have I ever gone to a vineyard for a picnic.',
  'Never have I ever stayed at a luxury treehouse.',
  'Never have I ever visited a vineyard for a wine tasting.',
  'Never have I ever attended a secret pop-up rooftop event.',
  'Never have I ever had a private beach bonfire.',
  'Never have I ever attended a rooftop yoga class.',
  'Never have I ever stayed at a desert villa.',
  'Never have I ever attended a vineyard concert.',
  'Never have I ever attended a rooftop brunch event.',
  'Never have I ever stayed at a beachfront hotel.',
  'Never have I ever attended a vineyard wedding.',
  'Never have I ever gone on a rooftop dinner date.',
  'Never have I ever taken a moonlit stroll on the beach.',
  'Never have I ever attended a pop-up rooftop art gallery.',
  'Never have I ever gone to a rooftop dinner party.',
  'Never have I ever stayed at a rooftop villa.',
  'Never have I ever attended a private beach dinner.',
  'Never have I ever taken a helicopter ride at sunset.',
  'Never have I ever had a sunset dinner on a boat.',
  'Never have I ever gone to a rooftop wine tasting.',
  'Never have I ever stayed at a vineyard hotel.',
  'Never have I ever taken a private boat tour at sunset.',
  'Never have I ever stayed at a rooftop cabin.',
  'Never have I ever gone on a private yacht tour.',
  'Never have I ever had a private dinner on the beach.',
  'Never have I ever attended a rooftop party with a view.',
  'Never have I ever attended a private vineyard tasting event.',
  'Never have I ever had a romantic rooftop dinner.',
  'Never have I ever taken a private moonlit beach walk.',
  'Never have I ever attended a secret rooftop yoga class.',
  'Never have I ever gone to a vineyard for a sunset picnic.',
  'Never have I ever had a private vineyard tour and tasting.',
  'Never have I ever stayed at a luxury beach villa.',
  'Never have I ever had a sunset dinner at a vineyard.',
  'Never have I ever gone on a rooftop wine tasting tour.',
  'Never have I ever attended a private rooftop concert.',
  'Never have I ever stayed at a beachfront resort.',
  'Never have I ever gone on a rooftop yoga retreat.',
  'Never have I ever gone to a secret vineyard party.',
  'Never have I ever gone on a rooftop art gallery tour.'
]);

// Game state
const currentPrompt = ref('');
const isGameStarted = ref(false);
const customPrompt = ref('');

// Start game and display the first random prompt
const startGame = () => {
  if (!isGameStarted.value) {
    isGameStarted.value = true;
    nextPrompt();
  }
};

// Generate the next random prompt
const nextPrompt = () => {
  const randomIndex = Math.floor(Math.random() * prompts.value.length);
  currentPrompt.value = prompts.value[randomIndex];
};

// Add custom prompt
const addCustomPrompt = () => {
  if (customPrompt.value.trim()) {
    prompts.value.push(customPrompt.value.trim());
    customPrompt.value = ''; // Reset input field
  }
};
</script>

<template>
  <div class="h-full bg-gray-800 flex flex-col items-center justify-center text-white">
    <h1 class="text-4xl font-bold mb-10">Never Have I Ever</h1>

    <!-- Start Game Button -->
    <div v-if="!isGameStarted" class="text-center">
      <button @click="startGame" class="bg-green-500 text-white px-6 py-2 rounded-lg hover:bg-green-600 transition">
        Start Game
      </button>
    </div>

    <!-- Game Area -->
    <div v-if="isGameStarted" class="w-full max-w-lg text-center">
      <h2 class="text-2xl font-bold mb-4">Current Prompt:</h2>
      <p class="text-xl bg-white text-black p-4 rounded-lg">{{ currentPrompt }}</p>

      <!-- Next Prompt Button -->
      <button @click="nextPrompt" class="mt-8 bg-blue-500 text-white px-6 py-2 rounded-lg hover:bg-blue-600 transition">
        Next Prompt
      </button>
    </div>

    <!-- Custom Prompt Input -->
    <div v-if="isGameStarted" class="mt-8 w-full max-w-lg">
      <h3 class="text-xl font-bold mb-4">Add Your Own Prompt:</h3>
      <input
          v-model="customPrompt"
          type="text"
          placeholder="Enter custom prompt"
          class="bg-gray-200 text-black px-3 py-2 rounded-md w-full mb-4"
      />
      <button @click="addCustomPrompt" class="bg-yellow-500 text-white px-6 py-2 rounded-lg hover:bg-yellow-600 transition">
        Add Prompt
      </button>
    </div>
  </div>
</template>

<style scoped>
/* Additional styling can be added here */
</style>
